name: Letsboot Fork Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install webview dependencies
      run: cd webview-ui && npm ci
    
    - name: Package extension
      run: |
        npm install -g @vscode/vsce
        vsce package --out cline-latest.vsix
    
    - name: Get version from package.json
      id: package-version
      run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
    
    - name: Create versioned copy
      run: cp cline-latest.vsix cline-v${{ steps.package-version.outputs.version }}.vsix
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.package-version.outputs.version }}
        release_name: Letsboot Fork v${{ steps.package-version.outputs.version }}
        draft: false
        prerelease: false
    
    - name: Upload latest VSIX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cline-latest.vsix
        asset_name: cline-latest.vsix
        asset_content_type: application/zip
    
    - name: Upload versioned VSIX
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./cline-v${{ steps.package-version.outputs.version }}.vsix
        asset_name: cline-v${{ steps.package-version.outputs.version }}.vsix
        asset_content_type: application/zip
    
    - name: Update latest tag
      run: |
        git tag -f latest
        git push origin latest --force
